# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(verbose_name='Created Date')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.Merchant')),
            ],
        ),
    ]
