# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_auto_20170523_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('v', 'v'), ('s', 's'), ('c', 'c')], default='s', max_length=1),
        ),
    ]
