# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_auto_20170523_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_status',
            field=models.CharField(choices=[('authorized', 'authorized'), ('declined', 'declined'), ('settled', 'settled')], default='settled', max_length=10),
        ),
    ]
