# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0005_transaction_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cardnumber',
            field=models.CharField(max_length=16),
        ),
    ]
