# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-28 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0006_auto_20170523_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='approved_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
